### ISSUE TITLE
Subtitle decoding api is inconsistent with video and audio decoding

### ISSUE THREAD

**Issue by Dr-42** [shssoichiro/ffmpeg-the-third#10]
For subtitles, there is just a decode method instead of the send_packet and receive frame. For that there needs to be a Frame(Subtitle) type in the frames folder I believe.
Is this api design intentional?

I don't have much prior experience working with ffmpeg, I just want to shows subtitles using the egui-video crate in my own app.

Please and Thank you.

**Comment by FreezyLemon** [comment]
This is intentional. This Rust library is a relatively thin wrapper around the FFmpeg API, and they use a function called [avcodec_subtitle_decode2](https://ffmpeg.org/doxygen/6.0/group__lavc__decoding.html#ga5c30b73f0ec105f93d4e86464f541f21) for subtitles instead of their usual packet-based API.
