### ISSUE TITLE
avresample is not handled correctly

### ISSUE THREAD

**Issue by FreezyLemon** [shssoichiro/ffmpeg-the-third#19]
libavresample is only supported up until FFmpeg 4.4.X and has been removed starting with FFmpeg 5.0.

This is handled in the sys/build.rs by checking `ffmpeg_major_version()` in a few places.

`ffmpeg_major_version` is calculated by parsing the `CARGO_PKG_VERSION`. This means that e.g. `1.2.3+ffmpeg-6.0` will result in a major version of `6`, meaning avresample will never get linked. However, even newer crate versions support older FFmpeg linkage, so this doesn't make sense (I can use FFmpeg libraries versioned at 4.4 with a crate version supporting 6.X).

I think the only real fix to this is figuring out the actual FFmpeg version at build.rs-runtime.

**Comment by FreezyLemon** [comment]
I've thought about how to approach this. Keeping in mind #11, it might make sense to use the `clang` crate to parse the respective header files (`version.h`, `version_major.h`) and directly read the library versions.
Sadly, I think I've hit [this bug](https://github.com/KyleMayes/clang-rs/issues/45) which stalled my progress on this, at least for now.

**Comment by nsabovic** [comment]
I've updated #11 so that it generates the same cargo output as the current implementation so it passes all the tests. It also reads library versions, if I understood you correctly, using clang::sonar API. Take a look and see if it resolves this issue.

**Comment by FreezyLemon** [comment]
Looks good at first glance. Appreciate you updating the PR and adding this :+1:
I'll take a proper look as soon as I have some time. Having version detection at build time would allow us to do some neat stuff
