### ISSUE TITLE
missing `libavutil.pc` build failure on windows

### ISSUE THREAD

**Issue by anandijain** [shssoichiro/ffmpeg-the-third#45]
thank you very much for keeping rust ffmpeg support alive.

I have been having a hell of a time trying to get any of the rust ffmpeg bindings to work for me on windows. 
I followed the build instructions linked in the readme (installing LLVM and full-shared build of ffmpeg and putting on path). 

The issue (apparently) is that pkg-config files don't seem to be included in the Gyan full shared builds although I don't know enough about it to be sure.

Here is the log I keep running into when trying to build/run my crate that has `ffmpeg-the-third` as a dependency: 
```
 --- stderr
  thread 'main' panicked at C:\Users\anand\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ffmpeg-sys-the-third-1.1.1+ffmpeg-6.0\build.rs:714:14:
  called `Result::unwrap()` on an `Err` value: 
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags libavutil

  The system library `libavutil` required by crate `ffmpeg-sys-the-third` was not found.
  The file `libavutil.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `libavutil.pc`.

  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panicking.rs:645
     1: core::panicking::panic_fmt
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\core\src\panicking.rs:72
     2: core::result::unwrap_failed
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\core\src\result.rs:1649
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::link_to_libraries::{{closure}}
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I was able to find someone else that has run into the issue but got no response to the issue of missing `.pc`
https://www.reddit.com/r/ffmpeg/comments/jr1poj/missing_libavutil_package/

Thanks again!

**Comment by anandijain** [comment]
apologies for the spam. the solution is to just install ffmpeg with vcpkg.

**Comment by FreezyLemon** [comment]
The GyanD files don't include pkg-config files because `.pc` files would need to know where you install your FFmpeg libraries. That's not really possible if you just download a zipfile and extract it somewhere.

You can always set the environment variable `FFMPEG_DIR` to disable all of the auto-detection and just tell the build script directly where it is.

In PowerShell (sorry, don't know how to do it in cmd):
```pwsh
$env:FFMPEG_DIR="C:\Users\MyUser\Downloads\ffmpeg"
```

**Comment by FreezyLemon** [comment]
Oh, seems like you solved it while I was typing. No worries, a genuine question is never spam :)
